trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '11'
  mavenVersion: '3.6.3'
  appName: 'car-marketplace-app'

steps:
- task: MavenAuthenticate@0
  inputs:
    mavenFeed: 'your-maven-feed'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests=true'
    mavenVersionOption: 'Default'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    codeCoverageToolOption: 'None'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/car-marketplace-app/target'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'your-azure-subscription'
    appName: '$(appName)'
    package: '$(Build.ArtifactStagingDirectory)/**/*.jar'
    runtimeStack: 'JAVA|11'